-- Onboarding questions table and seed data

create table if not exists public.onboarding_questions (
  id uuid primary key default gen_random_uuid(),
  question_code text not null unique,
  grade_level integer not null,
  subject text not null,
  unit text null,
  topic text null,
  question_text text not null,
  options text[] not null,
  correct_option text not null,
  order_index integer not null default 1,
  created_at timestamptz not null default now()
);

-- Insert onboarding questions (skip duplicates by question_code)
insert into public.onboarding_questions (
  question_code,
  grade_level,
  subject,
  unit,
  topic,
  question_text,
  options,
  correct_option,
  order_index
)
select
  v.question_code,
  v.grade_level,
  v.subject,
  v.unit,
  v.topic,
  v.question_text,
  v.options,
  v.correct_option,
  v.order_index
from (values
  -- Grade 8 (used for Grade 9 onboarding)
  ('G8_MATH_01', 8, 'math', null, 'Rational Numbers',
   'What is the result of converting the mixed number 3 1/5 into a single fraction?',
   array['16/5','4/5','14/5','9/5'], 'A', 1),
  ('G8_BIO_01', 8, 'biology', null, 'Human Biology',
   'Which part of the human brain is primarily responsible for maintaining posture, balance, and the coordination of voluntary muscle movements?',
   array['Cerebrum','Cerebellum','Brainstem','Thalamus'], 'B', 2),
  ('G8_MATH_02', 8, 'math', null, 'Measurement and Geometry',
   'If the area of a square is 196 cm^2, what is the length of one side of that square?',
   array['11 cm','13 cm','14 cm','19 cm'], 'B', 3),
  ('G8_PHYS_01', 8, 'physics', null, 'Physics - Optics',
   'A light ray strikes a plane mirror at an angle of incidence of 35 degrees. According to the laws of reflection, what is the resulting angle of reflection?',
   array['35 degrees','55 degrees','70 degrees','90 degrees'], 'A', 4),
  ('G8_MATH_03', 8, 'math', null, 'Coordinate Geometry',
   'If a point (x, y) is located in the fourth quadrant, which of the following statements regarding the signs of the coordinates is true?',
   array['x > 0 and y > 0','x > 0 and y < 0','x < 0 and y > 0','x < 0 and y < 0'], 'B', 5),
  ('G8_CHEM_01', 8, 'chemistry', null, 'Chemistry - Atomic Structure',
   'Which subatomic particles are found within the nucleus of an atom?',
   array['Electrons and Protons','Electrons and Neutrons','Protons and Neutrons','Protons only'], 'C', 6),
  ('G8_BIO_02', 8, 'biology', null, 'Environmental Science',
   'What is the primary environmental impact associated with the excessive use of chlorofluorocarbons (CFCs) in the atmosphere?',
   array['Acid rain','Ozone layer depletion','Eutrophication','Soil erosion'], 'B', 7),
  ('G8_MATH_04', 8, 'math', null, 'Geometry of Circles',
   'In the context of circle properties, what is the definition of a line that touches the circle at exactly one point?',
   array['Secant line','Chord','Diameter','Tangent line'], 'D', 8),
  ('G8_MATH_05', 8, 'math', null, 'Probability',
   'What is the numerical probability of an impossible event occurring?',
   array['0','1/2','1/4','1'], 'D', 9),
  ('G8_PHYS_02', 8, 'physics', null, 'Physics - Mechanics',
   'In a simple machine, what is the term used for the ratio of the load (output force) to the effort (input force)?',
   array['Efficiency','Velocity Ratio','Mechanical Advantage','Power'], 'C', 10),

  -- Grade 9 (used for Grade 10 onboarding)
  ('G9_MATH_01', 9, 'math', 'Unit 1: Further on Sets', 'Set Description and Notation',
   'Which of the following represents the set of all prime numbers less than 10 using the roster (listing) method?',
   array['{1, 2, 3, 5, 7, 9}','{2, 3, 5, 7}','{3, 5, 7, 9}','{2, 4, 6, 8}'], 'B', 1),
  ('G9_PHYS_01', 9, 'physics', 'Unit 2: Physical Quantities', 'Classification of Physical Quantities',
   'Which of the following physical quantities is classified as a vector quantity?',
   array['Mass','Time','Displacement','Temperature'], 'C', 2),
  ('G9_MATH_02', 9, 'math', 'Unit 2: The Number System', 'Real Numbers',
   'In the hierarchy of the real number system, which of the following statements is always true?',
   array['Every rational number is an integer.','Every irrational number is a real number.','The set of whole numbers is not a subset of integers.','All real numbers are rational numbers.'], 'B', 3),
  ('G9_MATH_03', 9, 'math', 'Unit 5: Introduction to Trigonometry', 'Trigonometric Ratios',
   'In a right-angled triangle, if the adjacent side to angle theta is 4 cm and the hypotenuse is 5 cm, what is the value of cos(theta)?',
   array['0.8','0.6','1.25','0.75'], 'A', 4),
  ('G9_PHYS_02', 9, 'physics', 'Unit 4: Force, Work, Energy and Power', 'Newton''s Laws of Motion',
   'According to Newton''s Second Law of Motion, if the net force acting on an object is doubled while its mass remains constant, what happens to the acceleration of the object?',
   array['It is halved','It is doubled','It remains the same','It becomes four times larger'], 'B', 5),
  ('G9_PHYS_03', 9, 'physics', 'Unit 5: Simple Machines', 'Mechanical Advantage and Efficiency',
   'What is the term for the ratio of the distance moved by the effort to the distance moved by the load in a simple machine?',
   array['Mechanical Advantage','Efficiency','Velocity Ratio','Power Output'], 'C', 6),
  ('G9_CHEM_01', 9, 'chemistry', 'Unit 3: Structure of the Atom', 'Composition of an Atom and Isotopes',
   'Atoms of the same element that have the same number of protons but different numbers of neutrons are known as:',
   array['Isomers','Isotopes','Allotropes','Isobars'], 'B', 7),
  ('G9_BIO_01', 9, 'biology', 'Unit 3: Cells', 'Cell Structure',
   'Which organelle is often referred to as the ''powerhouse'' of the cell because it is the site where cellular respiration occurs to produce energy (ATP)?',
   array['Nucleus','Chloroplast','Mitochondrion','Ribosome'], 'C', 8),
  ('G9_BIO_02', 9, 'biology', 'Unit 2: Characteristics and Classification of Organisms', 'Taxonomy',
   'In the modern biological classification system, which of the following taxonomic levels is the most specific?',
   array['Kingdom','Phylum','Genus','Species'], 'D', 9),
  ('G9_CHEM_02', 9, 'chemistry', 'Unit 5: Chemical Bonding', 'Ionic Bonding',
   'What type of chemical bond is formed specifically by the complete transfer of one or more electrons from one atom to another, resulting in electrostatic attraction between oppositely charged ions?',
   array['Covalent bond','Metallic bond','Ionic bond','Hydrogen bond'], 'C', 10),

  -- Grade 10 (used for Grade 11 onboarding)
  ('G10_MATH_01', 10, 'math', 'Unit 2: Polynomial Functions', 'Theorems on Polynomial Functions',
   'According to the Remainder Theorem, what is the remainder when the polynomial P(x) = x^3 - 2x^2 + 4x - 5 is divided by (x - 2)?',
   array['3','-5','0','7'], 'A', 1),
  ('G10_MATH_02', 10, 'math', 'Unit 3: Exponential and Logarithmic Functions', 'Solving Logarithmic Equations',
   'What is the value of x in the equation log_3(x) = 4?',
   array['12','64','81','7'], 'C', 2),
  ('G10_MATH_03', 10, 'math', 'Unit 5: Circles', 'Angle Properties of Circles',
   'If an inscribed angle in a circle intercepts an arc of 100 degrees, what is the measure of the inscribed angle?',
   array['100 degrees','50 degrees','200 degrees','90 degrees'], 'B', 3),
  ('G10_CHEM_01', 10, 'chemistry', 'Unit 1: Chemical Reactions and Stoichiometry', 'The Mole Concept',
   'What is the mass of 2 moles of Calcium Carbonate (CaCO3)? (Atomic masses: Ca = 40, C = 12, O = 16)',
   array['100 g','200 g','50 g','150 g'], 'B', 4),
  ('G10_CHEM_02', 10, 'chemistry', 'Unit 3: Important Inorganic Compounds', 'Acids and Bases',
   'Which of the following substances would most likely have a pH value less than 7?',
   array['Baking Soda','Ammonia Solution','Lemon Juice','Bleach'], 'C', 5),
  ('G10_BIO_01', 10, 'biology', 'Unit 4: Cell Division', 'Mitosis and Meiosis',
   'During which phase of mitosis do the sister chromatids separate and move toward opposite poles of the cell?',
   array['Prophase','Metaphase','Anaphase','Telophase'], 'C', 6),
  ('G10_BIO_02', 10, 'biology', 'Unit 3: Biochemical Molecules', 'Proteins and Enzymes',
   'What is the primary function of enzymes in biochemical reactions within a living organism?',
   array['Providing structural support to cells','Storing genetic information','Acting as biological catalysts to speed up reactions','Serving as the primary source of energy'], 'C', 7),
  ('G10_PHYS_01', 10, 'physics', 'Unit 1: Vector Quantities', 'Vector Addition',
   'Using the graphical method of vector addition, if two vectors are added head-to-tail, what is the name of the single vector that represents the sum of these two vectors?',
   array['Scalar sum','Resultant vector','Component vector','Equilibrant vector'], 'B', 8),
  ('G10_PHYS_03', 10, 'physics', 'Unit 6: Electromagnetic Waves and Geometrical Optics', 'Mirrors and Lenses',
   'Which type of lens is thinner at the center than at the edges and causes parallel rays of light to spread out (diverge)?',
   array['Convex lens','Biconvex lens','Concave lens','Planoconvex lens'], 'C', 9),
  ('G10_PHYS_02', 10, 'physics', 'Unit 4: Static and Current Electricity', 'Ohm''s Law',
   'According to Ohm''s Law, if the resistance in a circuit is kept constant and the voltage is doubled, what happens to the current flowing through the circuit?',
   array['It is halved','It remains the same','It is doubled','It is quadrupled'], 'C', 10),

  -- Grade 11 (used for Grade 12 onboarding)
  ('G11_PHYS_01', 11, 'physics', 'Unit 2: Vectors', 'Analytical Method of Vector Addition',
   'A vector A has a magnitude of 10 units and makes an angle of 60 degrees with the positive x-axis. What are the x and y components (Ax, Ay) of this vector?',
   array['Ax = 5.0, Ay = 8.66','Ax = 8.66, Ay = 5.0','Ax = 10.0, Ay = 0.0','Ax = 7.07, Ay = 7.07'], 'A', 1),
  ('G11_PHYS_02', 11, 'physics', 'Unit 3: Motion in One and Two Dimensions', 'Vertical Motion (Projectile Motion)',
   'An object is projected horizontally from the top of a cliff with a velocity of 20 m/s. If it takes 3 seconds to hit the ground, what is the height of the cliff? (Take g = 9.8 m/s^2)',
   array['29.4 m','44.1 m','60.0 m','88.2 m'], 'B', 2),
  ('G11_PHYS_03', 11, 'physics', 'Unit 4: Dynamics', 'Work, Energy and Power',
   'A 5 kg block is pushed 10 meters along a horizontal surface by a constant force of 20 N acting at an angle of 30 degrees to the horizontal. How much work is done by the force?',
   array['200 J','173.2 J','100 J','500 J'], 'B', 3),
  ('G11_CHEM_01', 11, 'chemistry', 'Unit 1: Atomic Structure and Periodic Properties', 'Quantum Numbers',
   'Which quantum number determines the orientation of an atomic orbital in space?',
   array['Principal quantum number (n)','Angular momentum quantum number (l)','Magnetic quantum number (ml)','Electron spin quantum number (ms)'], 'C', 4),
  ('G11_CHEM_02', 11, 'chemistry', 'Unit 2: Chemical Bonding', 'Chemical Bonding Theories',
   'According to the Valence Bond Theory, what type of bond is formed by the head-to-head overlap of atomic orbitals along the internuclear axis?',
   array['Pi (pi) bond','Sigma (sigma) bond','Ionic bond','Hydrogen bond'], 'B', 5),
  ('G11_MATH_01', 11, 'math', 'Unit 1: Relations and Functions', 'Types of Functions',
   'A function f is defined such that for every element in the domain, there is exactly one unique element in the codomain, and every element in the codomain is mapped to by at least one element in the domain. What is this type of function called?',
   array['Injective (One-to-One)','Surjective (Onto)','Bijective','Constant'], 'B', 6),
  ('G11_MATH_02', 11, 'math', 'Unit 2: The Number System', 'Rational Expressions',
   'Which of the following represents the domain of the rational expression: f(x) = (x + 5) / (x^2 - 9)?',
   array['All real numbers','{x | x != -5}','{x | x != 3 and x != -3}','{x | x > 9}'], 'C', 7),
  ('G11_MATH_03', 11, 'math', 'Advanced Algebra', 'Rational Matrices',
   'If a 2x2 matrix A has entries that are all rational expressions, what is required for the inverse matrix A^-1 to exist?',
   array['The determinant must be a non-zero rational expression.','All entries must be constant integers.','The matrix must be a diagonal matrix.','The sum of the entries must be positive.'], 'A', 8),
  ('G11_BIO_01', 11, 'biology', 'Unit 3: Enzymes', 'Enzyme-Substrate Models',
   'Which model of enzyme action suggests that the enzyme''s active site changes its shape slightly to fit the substrate more securely upon binding?',
   array['Lock and Key Model','Induced Fit Model','Fluid Mosaic Model','Static Template Model'], 'C', 9),
  ('G11_BIO_02', 11, 'biology', 'Unit 4: Genetics', 'DNA Structure and Function',
   'In a DNA molecule, if the percentage of Adenine (A) is 30 percent, what would be the expected percentage of Guanine (G) according to Chargaff''s rules?',
   array['30 percent','70 percent','20 percent','50 percent'], 'C', 10)
) as v(
  question_code,
  grade_level,
  subject,
  unit,
  topic,
  question_text,
  options,
  correct_option,
  order_index
)
left join public.onboarding_questions q
  on q.question_code = v.question_code
where q.question_code is null;
